export const CONTRIBUTION_LIST_REQUEST = 'CONTRIBUTION_LIST_REQUEST';
export const CONTRIBUTION_LIST_SUCCESS = 'CONTRIBUTION_LIST_SUCCESS';
export const CONTRIBUTION_LIST_FAIL = 'CONTRIBUTION_LIST_FAIL';

export const CONTRIBUTION_DETAIL_REQUEST = 'CONTRIBUTION_DETAIL_REQUEST';
export const CONTRIBUTION_DETAIL_SUCCESS = 'CONTRIBUTION_DETAIL_SUCCESS';
export const CONTRIBUTION_DETAIL_FAIL = 'CONTRIBUTION_DETAIL_FAIL';
